<?php

use Illuminate\Database\Seeder;

class AbusesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qweqweweqweqwe',
                'subject' => '',
                'created_at' => '2020-08-18 12:10:20',
                'updated_at' => '2020-08-18 12:10:20',
            ],[
                'id' => '2',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwertyqwerty',
                'subject' => '',
                'created_at' => '2020-08-18 12:11:51',
                'updated_at' => '2020-08-18 12:11:51',
            ],[
                'id' => '3',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwertet erter terter',
                'subject' => '',
                'created_at' => '2020-08-18 12:13:29',
                'updated_at' => '2020-08-18 12:13:29',
            ],[
                'id' => '4',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwerty qweert',
                'subject' => '',
                'created_at' => '2020-08-25 12:06:00',
                'updated_at' => '2020-08-25 12:06:00',
            ],[
                'id' => '5',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwerty erter',
                'subject' => '',
                'created_at' => '2020-08-25 12:06:18',
                'updated_at' => '2020-08-25 12:06:18',
            ],[
                'id' => '6',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'rtytry rtyrty',
                'subject' => '',
                'created_at' => '2020-08-25 12:08:34',
                'updated_at' => '2020-08-25 12:08:34',
            ],[
                'id' => '7',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'we werw werwerer',
                'subject' => '',
                'created_at' => '2020-08-25 12:09:43',
                'updated_at' => '2020-08-25 12:09:43',
            ],[
                'id' => '8',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwe wrwe were',
                'subject' => '',
                'created_at' => '2020-08-25 12:10:12',
                'updated_at' => '2020-08-25 12:10:12',
            ],[
                'id' => '9',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'ert ertert erter',
                'subject' => '',
                'created_at' => '2020-08-25 12:11:05',
                'updated_at' => '2020-08-25 12:11:05',
            ],[
                'id' => '10',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwe qweqwe qwew',
                'subject' => '',
                'created_at' => '2020-08-25 12:11:33',
                'updated_at' => '2020-08-25 12:11:33',
            ],[
                'id' => '11',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qqwwewewewe',
                'subject' => '',
                'created_at' => '2020-08-25 13:10:02',
                'updated_at' => '2020-08-25 13:10:02',
            ],[
                'id' => '12',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'fghfg fghfghgh',
                'subject' => '',
                'created_at' => '2020-08-28 13:07:34',
                'updated_at' => '2020-08-28 13:07:34',
            ],[
                'id' => '13',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwerty erer',
                'subject' => '',
                'created_at' => '2020-08-28 13:09:44',
                'updated_at' => '2020-08-28 13:09:44',
            ],[
                'id' => '14',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qweqrqw qwrw',
                'subject' => '',
                'created_at' => '2020-08-28 13:11:49',
                'updated_at' => '2020-08-28 13:11:49',
            ],[
                'id' => '15',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'fghfghghfghfghfghg',
                'subject' => '',
                'created_at' => '2020-08-28 13:12:10',
                'updated_at' => '2020-08-28 13:12:10',
            ],[
                'id' => '16',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'fghfgh fghfgh',
                'subject' => '',
                'created_at' => '2020-08-28 13:12:44',
                'updated_at' => '2020-08-28 13:12:44',
            ],[
                'id' => '17',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'fghfgh fghfgh',
                'subject' => '',
                'created_at' => '2020-08-28 13:13:14',
                'updated_at' => '2020-08-28 13:13:14',
            ],[
                'id' => '18',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'ert erterterter',
                'subject' => '',
                'created_at' => '2020-08-28 13:13:23',
                'updated_at' => '2020-08-28 13:13:23',
            ],[
                'id' => '19',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'werwe werwer',
                'subject' => '',
                'created_at' => '2020-08-28 13:13:47',
                'updated_at' => '2020-08-28 13:13:47',
            ],[
                'id' => '20',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'wer werwer',
                'subject' => '',
                'created_at' => '2020-08-28 13:14:16',
                'updated_at' => '2020-08-28 13:14:16',
            ],[
                'id' => '21',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwe qweqwew',
                'subject' => '',
                'created_at' => '2020-08-28 13:15:24',
                'updated_at' => '2020-08-28 13:15:24',
            ],[
                'id' => '22',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwe qweqwewe',
                'subject' => '',
                'created_at' => '2020-08-28 13:16:12',
                'updated_at' => '2020-08-28 13:16:12',
            ],[
                'id' => '23',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'wer werwerwer',
                'subject' => '',
                'created_at' => '2020-08-28 13:16:41',
                'updated_at' => '2020-08-28 13:16:41',
            ],[
                'id' => '24',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'fghfg fghfghfgh',
                'subject' => '',
                'created_at' => '2020-08-28 13:17:12',
                'updated_at' => '2020-08-28 13:17:12',
            ],[
                'id' => '25',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'fg hfghfg hfghf',
                'subject' => '',
                'created_at' => '2020-08-28 13:17:18',
                'updated_at' => '2020-08-28 13:17:18',
            ],[
                'id' => '26',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwe qwewew qwe',
                'subject' => '',
                'created_at' => '2020-08-28 13:19:43',
                'updated_at' => '2020-08-28 13:19:43',
            ],[
                'id' => '27',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'sdfsd sdfsdfdf',
                'subject' => '',
                'created_at' => '2020-08-28 13:20:32',
                'updated_at' => '2020-08-28 13:20:32',
            ],[
                'id' => '28',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwerty rtyrty',
                'subject' => '',
                'created_at' => '2020-08-28 13:22:53',
                'updated_at' => '2020-08-28 13:22:53',
            ],[
                'id' => '29',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qweqweqw w',
                'subject' => '',
                'created_at' => '2020-08-28 13:25:31',
                'updated_at' => '2020-08-28 13:25:31',
            ],[
                'id' => '30',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'sdf sdfsdfsdfdsfds',
                'subject' => '',
                'created_at' => '2020-08-28 13:44:22',
                'updated_at' => '2020-08-28 13:44:22',
            ],[
                'id' => '31',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'dfg dfgdf gdfgdfg',
                'subject' => '',
                'created_at' => '2020-08-28 13:53:02',
                'updated_at' => '2020-08-28 13:53:02',
            ],[
                'id' => '32',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qweqwe qweqw',
                'subject' => 'suggestion',
                'created_at' => '2020-09-10 10:24:21',
                'updated_at' => '2020-09-10 10:24:21',
            ],[
                'id' => '33',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'errttttttt',
                'subject' => 'suggestion',
                'created_at' => '2020-09-10 10:25:54',
                'updated_at' => '2020-09-10 10:25:54',
            ],[
                'id' => '34',
                'user_id' => '2',
                'name' => 'Афонина Алина Викторовна',
                'email' => 's-fr@yandex.ru',
                'text' => 'qwerty eee ee e',
                'subject' => 'suggestion',
                'created_at' => '2020-09-10 11:27:55',
                'updated_at' => '2020-09-10 11:27:55',
            ],
        ];
        DB::table('abuses')->insert($data);
    }
}
